echo "First Value is : $1"
echo "Second Value is: $2"
echo "Third Valus is : $3"
echo "value of Arguments Passed at command line : $*"
echo "value of arguments passed at command line : $@"
echo "Count of arguments passed at command line : $#"
echo "Name of script is : $0"
echo "PID of program is : $$" 
echo "Last return code: $?"
